services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # 컨테이너 내부 경로와 연결
    networks:
      - blog-network

volumes:
  mysql_data: # Docker 볼륨 생성

networks:
  blog-network:
    driver: bridge  # 브릿지 네트워크 사용